#!/usr/bin/env bash
#
#  atcoind The atcoin core server.
#
#
# chkconfig: 345 80 20
# description: atcoind
# processname: atcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/atcoind, see below
if [ -f /etc/sysconfig/atcoind ]; then
        . /etc/sysconfig/atcoind
fi

RETVAL=0

prog=atcoind
# you can override the lockfile via ATCOIND_LOCKFILE in /etc/sysconfig/atcoind
lockfile=${ATCOIND_LOCKFILE-/var/lock/subsys/atcoind}

# atcoind defaults to /usr/bin/atcoind, override with ATCOIND_BIN
atcoind=${ATCOIND_BIN-/usr/bin/atcoind}

# atcoind opts default to -disablewallet, override with ATCOIND_OPTS
atcoind_opts=${ATCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $atcoind $atcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
