description "ATCOIN Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env ATCOIND_BIN="/usr/bin/atcoind"
env ATCOIND_USER="atcoin"
env ATCOIND_GROUP="atcoin"
env ATCOIND_PIDDIR="/var/run/atcoind"
# upstart can't handle variables constructed with other variables
env ATCOIND_PIDFILE="/var/run/atcoind/atcoind.pid"
env ATCOIND_CONFIGFILE="/etc/atcoin/atcoin.conf"
env ATCOIND_DATADIR="/var/lib/atcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # atcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$ATCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run atcoind."
        echo "The setting must appear in $ATCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"ATCOIN Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$ATCOIND_PIDDIR"
    chmod 0755 "$ATCOIND_PIDDIR"
    chown $ATCOIND_USER:$ATCOIND_GROUP "$ATCOIND_PIDDIR"
    chown $ATCOIND_USER:$ATCOIND_GROUP "$ATCOIND_CONFIGFILE"
    chmod 0660 "$ATCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$ATCOIND_PIDFILE" \
    --chuid $ATCOIND_USER:$ATCOIND_GROUP \
    --exec "$ATCOIND_BIN" \
    -- \
    -pid="$ATCOIND_PIDFILE" \
    -conf="$ATCOIND_CONFIGFILE" \
    -datadir="$ATCOIND_DATADIR" \
    -disablewallet \
    -daemon

